# Generated by Django 5.2.3 on 2025-06-26 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_staff'),
    ]

    operations = [
    ]
