# Generated by Django 5.2.3 on 2025-07-03 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_notificationsetting_delete_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='low_stock_alert_sent',
            field=models.BooleanField(default=False),
        ),
    ]
